In [5]:
import numpy as np

In [13]:
# how we can create a user define array
a=[]
size=int(input("enter the size"))
for i in range(size):
    value=int(input("enter the value"))
    a.append(value)
b=np.array(a)
b

enter the size 2
enter the value 23
enter the value 34


array([23, 34])

In [59]:
a=[[12,34,45],[655,676,343,],[333,56,67]]
(a)
print(type(a))
b=np.array(a)
b


<class 'list'>


array([[ 12,  34,  45],
       [655, 676, 343],
       [333,  56,  67]])

In [75]:
# numpy function

# 1  ->> zeros -> it will creaste an array in which all the values are zero.

a=np.zeros((2,3))
a





array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# 2,-> once method  ->> it will create an array in  which all the values aarre one

a=np.ones((3,4))
a
 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

<!-- 3-->> eye() --> -->it will create an array in which diagonal positional elements are 1 and rest all are 0.

 
a=np.eye(3)
a

In [105]:
a=np.eye(3)    # asymetric matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
a=np.eye(3)    # asymetric matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [95]:
a=np.eye(3,4)    # symetric matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [101]:
# 4.--> diag()  -->> it will create an array in whixh we can customizd our diagonal positional element

a=np.diag([1,56,89,700])
a

array([[  1,   0,   0,   0],
       [  0,  56,   0,   0],
       [  0,   0,  89,   0],
       [  0,   0,   0, 700]])

In [103]:
# 5 --> random module-->
# a ->ot[ generation
# b --> dataset -> 1 dummy column add
# c ->> randomly weights initialize

In [119]:
b=np.random.randint(1,20,4)
b

array([ 8, 11,  7, 18])

In [125]:
b=np.random.randn(3)
b

array([ 1.55961062, -1.39122022,  0.26953296])

In [129]:
b=np.random.rand(4) 
b

array([0.8178289 , 0.17179525, 0.35456781, 0.5775054 ])

In [167]:
np.random.seed(50)
b=np.random.randint(1,45,5)
b

array([33, 12, 34, 31,  5])

In [177]:
# how we can create a user define array

a=[]
value=int(input("enter the valye"))
for i in range(value):
    size=int(input("enter the number"))
    a.append(size)
b=np.array(a)
b

enter the valye 2
enter the number 12
enter the number 23


array([12, 23])

In [189]:
type(b)


numpy.ndarray

In [9]:
a=np.random.randint(1,100,72)
a

array([95, 81, 33, 63, 49, 20, 36, 17,  1, 74, 30, 59, 54, 22, 81, 55, 14,
       92, 24, 37, 81, 51, 56, 80, 83, 84, 66,  1, 44, 44, 14, 74, 78, 11,
       97, 79,  3, 91, 31, 85, 38, 71, 83, 71, 93,  8, 43, 43,  2, 59, 54,
       42, 96,  1, 46, 17, 98, 86, 91, 91, 60, 27, 73, 11, 32, 83,  8, 99,
        5, 32, 47, 27])

In [203]:
a.reshape(1,72)

array([[48, 70, 93,  7, 66, 37, 85, 37, 45, 54, 79,  5, 87, 44, 20, 97,
        38, 31, 63, 45, 44, 36, 28, 51, 59, 29, 32, 16,  6, 53, 56, 57,
        48, 69,  5, 19, 43, 18, 91, 73, 47, 12, 28, 28, 60,  8, 42, 66,
        54, 73, 36,  4, 22, 43, 68, 71, 57, 80, 96, 23,  1, 57, 76, 31,
        34, 15, 91, 23, 47,  7, 63, 31]])

In [207]:
# a.reshape(72,1)


In [211]:
a.reshape(12,6)

array([[48, 70, 93,  7, 66, 37],
       [85, 37, 45, 54, 79,  5],
       [87, 44, 20, 97, 38, 31],
       [63, 45, 44, 36, 28, 51],
       [59, 29, 32, 16,  6, 53],
       [56, 57, 48, 69,  5, 19],
       [43, 18, 91, 73, 47, 12],
       [28, 28, 60,  8, 42, 66],
       [54, 73, 36,  4, 22, 43],
       [68, 71, 57, 80, 96, 23],
       [ 1, 57, 76, 31, 34, 15],
       [91, 23, 47,  7, 63, 31]])

In [213]:
a.reshape(6,12)

array([[48, 70, 93,  7, 66, 37, 85, 37, 45, 54, 79,  5],
       [87, 44, 20, 97, 38, 31, 63, 45, 44, 36, 28, 51],
       [59, 29, 32, 16,  6, 53, 56, 57, 48, 69,  5, 19],
       [43, 18, 91, 73, 47, 12, 28, 28, 60,  8, 42, 66],
       [54, 73, 36,  4, 22, 43, 68, 71, 57, 80, 96, 23],
       [ 1, 57, 76, 31, 34, 15, 91, 23, 47,  7, 63, 31]])

In [217]:
a.reshape(2,36)

array([[48, 70, 93,  7, 66, 37, 85, 37, 45, 54, 79,  5, 87, 44, 20, 97,
        38, 31, 63, 45, 44, 36, 28, 51, 59, 29, 32, 16,  6, 53, 56, 57,
        48, 69,  5, 19],
       [43, 18, 91, 73, 47, 12, 28, 28, 60,  8, 42, 66, 54, 73, 36,  4,
        22, 43, 68, 71, 57, 80, 96, 23,  1, 57, 76, 31, 34, 15, 91, 23,
        47,  7, 63, 31]])

In [221]:
# a.reshape(36,2)

In [227]:
a.reshape(3,24)

array([[48, 70, 93,  7, 66, 37, 85, 37, 45, 54, 79,  5, 87, 44, 20, 97,
        38, 31, 63, 45, 44, 36, 28, 51],
       [59, 29, 32, 16,  6, 53, 56, 57, 48, 69,  5, 19, 43, 18, 91, 73,
        47, 12, 28, 28, 60,  8, 42, 66],
       [54, 73, 36,  4, 22, 43, 68, 71, 57, 80, 96, 23,  1, 57, 76, 31,
        34, 15, 91, 23, 47,  7, 63, 31]])

In [237]:
a.reshape(4,18)

array([[48, 70, 93,  7, 66, 37, 85, 37, 45, 54, 79,  5, 87, 44, 20, 97,
        38, 31],
       [63, 45, 44, 36, 28, 51, 59, 29, 32, 16,  6, 53, 56, 57, 48, 69,
         5, 19],
       [43, 18, 91, 73, 47, 12, 28, 28, 60,  8, 42, 66, 54, 73, 36,  4,
        22, 43],
       [68, 71, 57, 80, 96, 23,  1, 57, 76, 31, 34, 15, 91, 23, 47,  7,
        63, 31]])

In [241]:
a.reshape(6,12)

array([[48, 70, 93,  7, 66, 37, 85, 37, 45, 54, 79,  5],
       [87, 44, 20, 97, 38, 31, 63, 45, 44, 36, 28, 51],
       [59, 29, 32, 16,  6, 53, 56, 57, 48, 69,  5, 19],
       [43, 18, 91, 73, 47, 12, 28, 28, 60,  8, 42, 66],
       [54, 73, 36,  4, 22, 43, 68, 71, 57, 80, 96, 23],
       [ 1, 57, 76, 31, 34, 15, 91, 23, 47,  7, 63, 31]])

In [245]:
a.reshape(8,9)

array([[48, 70, 93,  7, 66, 37, 85, 37, 45],
       [54, 79,  5, 87, 44, 20, 97, 38, 31],
       [63, 45, 44, 36, 28, 51, 59, 29, 32],
       [16,  6, 53, 56, 57, 48, 69,  5, 19],
       [43, 18, 91, 73, 47, 12, 28, 28, 60],
       [ 8, 42, 66, 54, 73, 36,  4, 22, 43],
       [68, 71, 57, 80, 96, 23,  1, 57, 76],
       [31, 34, 15, 91, 23, 47,  7, 63, 31]])

In [247]:
# a.reshape()

In [ ]:
l